export const GET_JOB_LIST = 'GET_JOB_LIST';
export const GET_JOB_LIST_RESP = 'GET_JOB_LIST_RESP';

export const GET_AUTO_COMPLETE_LIST = 'GET_AUTO_COMPLETE_LIST';
export const GET_AUTO_COMPLETE_LIST_RESP = 'GET_AUTO_COMPLETE_LIST_RESP';

export const SELECTED_JOB_DATA = 'SELECTED_JOB_DATA';

export const SEARCH_BY_DESIGNATION = 'SEARCH_BY_DESIGNATION';
